import * as path from "path";
const {
  server: { SWAGGER, SWAGGER_FULL, SWAGGER_SCHEME },
} = require(path.resolve(__dirname, "./index"));

const {
  auth,
  options
} = require(path.resolve(__dirname, "./swagger_endpoints/index"));

const {
  Authentication,
  Errors,
  Options,
  Resource,
  Token
} = require(path.resolve(__dirname, "./swagger_endpoints/definitions/index"));

const swagger: object = {
  swagger: "2.0",
  info: {
    version: "1.0.0",
    title: "VCA DEVELOP TEAM, library API",
    description: "Developers api docs - VCA DEVELOP TEAM rest api library.",
    termsOfService: SWAGGER_FULL,
    contact: {
      name: "API Support",
      url: SWAGGER_FULL,
      email: "quintanaolvis@gmail.com",
    },
  },
  host: SWAGGER,
  basePath: "/api",
  schemes: SWAGGER_SCHEME,
  securityDefinitions: {
    Bearer: {
      type: "apiKey",
      name: "Authorization",
      in: "header",
      description:
        "For accessing the API a valid JWT token must be passed in all the queries in\nthe 'Authorization' header.\n\n\nA valid JWT token is generated by the API and returned as answer of a call\nto the route /user/login giving a valid user & password.\n\n\nThe following syntax must be used in the 'Authorization' header :\n\n    Bearer xxxxxx.yyyyyyy.zzzzzz\n",
    },
  },
  consumes: ["application/json"],
  produces: ["application/json"],
  paths: {
    ...auth,
    ...options
  },
  definitions: {
    Authentication,
    Errors,
    Options,
    Resource,
    Token
  },
};

export = swagger;
